--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-15 13:59:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 41981)
-- Name: mst_config; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.mst_config (
    id integer NOT NULL,
    config_key character varying(500) NOT NULL,
    config_value text,
    is_active boolean DEFAULT true,
    created_by uuid,
    created_at time without time zone DEFAULT now(),
    last_modified_by uuid,
    last_modified_at time without time zone DEFAULT now()
);


ALTER TABLE public.mst_config OWNER TO admin_db;

--
-- TOC entry 218 (class 1259 OID 41980)
-- Name: mst_config_id_seq; Type: SEQUENCE; Schema: public; Owner: admin_db
--

ALTER TABLE public.mst_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mst_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
    CYCLE
);


--
-- TOC entry 216 (class 1259 OID 41934)
-- Name: mst_transaction_type; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.mst_transaction_type (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    last_modified_by uuid,
    last_modified_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.mst_transaction_type OWNER TO admin_db;

--
-- TOC entry 215 (class 1259 OID 41933)
-- Name: mst_transaction_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin_db
--

ALTER TABLE public.mst_transaction_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mst_transaction_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9
    CACHE 1
    CYCLE
);


--
-- TOC entry 217 (class 1259 OID 41944)
-- Name: trn_transaction; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.trn_transaction (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    wallet_id uuid NOT NULL,
    transaction_type_id integer DEFAULT 1 NOT NULL,
    amount money DEFAULT 0 NOT NULL,
    reference text,
    is_active boolean DEFAULT true,
    created_by uuid,
    created_at timestamp without time zone DEFAULT now(),
    last_modified_by uuid,
    last_modified_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.trn_transaction OWNER TO admin_db;

--
-- TOC entry 220 (class 1259 OID 50165)
-- Name: vw_transaction_list_data; Type: VIEW; Schema: public; Owner: admin_db
--

CREATE VIEW public.vw_transaction_list_data AS
 SELECT trans.id AS transaction_id,
    trans.wallet_id,
    trans.transaction_type_id,
    typ.name AS transaction_type_name,
    trans.amount,
        CASE
            WHEN (trans.transaction_type_id = ANY (ARRAY[1, 2])) THEN 'Cash In'::text
            ELSE 'Cash Out'::text
        END AS cash_flow,
    trans.reference,
    trans.created_at AS transaction_date
   FROM (public.trn_transaction trans
     JOIN public.mst_transaction_type typ ON ((trans.transaction_type_id = typ.id)))
  WHERE (trans.is_active = true);


ALTER VIEW public.vw_transaction_list_data OWNER TO admin_db;

--
-- TOC entry 4867 (class 0 OID 41981)
-- Dependencies: 219
-- Data for Name: mst_config; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.mst_config (id, config_key, config_value, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
1	UrlClaimToken	http://simpleewallet-auth-service-1:7095/api/v1/Auth/claim-token	t	\N	17:13:54.915526	\N	17:13:54.915526
\.


--
-- TOC entry 4864 (class 0 OID 41934)
-- Dependencies: 216
-- Data for Name: mst_transaction_type; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.mst_transaction_type (id, name, description, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
1	Topup	Topup	t	\N	2025-04-12 20:35:36.130125	\N	2025-04-12 20:35:36.130125
2	Transfer In	Transfer In 	t	\N	2025-04-12 20:36:11.002988	\N	2025-04-12 20:36:11.002988
3	Transfer Out	Transfer Out	t	\N	2025-04-12 20:36:29.333947	\N	2025-04-12 20:36:29.333947
\.


--
-- TOC entry 4865 (class 0 OID 41944)
-- Dependencies: 217
-- Data for Name: trn_transaction; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.trn_transaction (id, wallet_id, transaction_type_id, amount, reference, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
d909cbac-422d-4199-aa67-fd99da517ba1	1add0b7e-a3b4-44a8-9f8b-652ee9cbf2e6	1	$19,000.00	\N	t	004ca24e-9a38-4104-8514-27e68133f013	2025-04-14 15:00:41.204263	004ca24e-9a38-4104-8514-27e68133f013	2025-04-14 15:00:41.231275
\.


--
-- TOC entry 4873 (class 0 OID 0)
-- Dependencies: 218
-- Name: mst_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_db
--

SELECT pg_catalog.setval('public.mst_config_id_seq', 1, true);


--
-- TOC entry 4874 (class 0 OID 0)
-- Dependencies: 215
-- Name: mst_transaction_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_db
--

SELECT pg_catalog.setval('public.mst_transaction_type_id_seq', 3, true);


--
-- TOC entry 4718 (class 2606 OID 41990)
-- Name: mst_config mst_config_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_config
    ADD CONSTRAINT mst_config_pkey PRIMARY KEY (id);


--
-- TOC entry 4714 (class 2606 OID 41943)
-- Name: mst_transaction_type mst_transaction_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_transaction_type
    ADD CONSTRAINT mst_transaction_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4716 (class 2606 OID 41956)
-- Name: trn_transaction trn_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.trn_transaction
    ADD CONSTRAINT trn_transaction_pkey PRIMARY KEY (id);


-- Completed on 2025-04-15 13:59:04

--
-- PostgreSQL database dump complete
--

