services:
  rabbitmq_wallet:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - simple_ewallet_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  auth-db:
    image: postgres:latest
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ewallet_db_auth
    ports:
      - "5433:5432"
    networks:
      - simple_ewallet_network
    volumes:
      - simple_ewallet_auth_db:/var/lib/postgresql/data
      - ./init/ewallet_db_auth.sql:/docker-entrypoint-initdb.d/init.sql

  wallet-db:
    image: postgres:latest
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ewallet_db_wallet
    ports:
      - "5434:5432"
    networks:
      - simple_ewallet_network
    volumes:
      - simple_ewallet_wallet_db:/var/lib/postgresql/data
      - ./init/ewallet_db_wallet.sql:/docker-entrypoint-initdb.d/init.sql

  transaction-db:
    image: postgres:latest
    container_name: transaction_db
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ewallet_db_transaction
    ports:
      - "5435:5432"
    networks:
      - simple_ewallet_network
    volumes:
      - simple_ewallet_transaction_db:/var/lib/postgresql/data
      - ./init/ewallet_db_transaction.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build:
      context: .
      dockerfile: SimpleEWallet.Auth/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7095
      - ConnectionStrings__DbAuthConnection=User ID=admin_db;Password=admin;Host=auth_db;Port=5432;Database=ewallet_db_auth;Pooling=true;
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq_wallet:
        condition: service_healthy
    ports:
      - "7095:7095"
    networks:
      - simple_ewallet_network

  wallet-service:
    build:
      context: .
      dockerfile: SimpleEWallet.Wallet/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7061
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq_wallet:
        condition: service_healthy
    ports:
      - "7061:7061"
    networks:
      - simple_ewallet_network

  transaction-service:
    build:
      context: .
      dockerfile: SimpleEWallet.Transaction/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7294
    depends_on:
      auth-db:
        condition: service_started
      rabbitmq_wallet:
        condition: service_healthy
    ports:
      - "7294:7294"
    networks:
      - simple_ewallet_network

  notification-service:
    build:
      context: .
      dockerfile: SimpleEWallet.Notification/Dockerfile
    ports:
      - "5004:80"
    networks:
      - simple_ewallet_network

  ewallet_pgadmin:
    image: dpage/pgadmin4
    container_name: ewallet_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@simpleewallet.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - "5051:80"
    networks:
      - simple_ewallet_network

networks:
  simple_ewallet_network:
    driver: bridge

volumes:
  simple_ewallet_auth_db:
  simple_ewallet_wallet_db:
  simple_ewallet_transaction_db:
